# Site settings
title: Ensemble Vocal Pierre de Lune
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Ensemble Vocal Pierre de Lune, direction Emmanuel Junod.
  Ensemble vocal basé à Genève, chant choral, musique classique.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.evpierredelune.ch" # the base hostname & protocol for your site
twitter_username: evpdl

# Build settings
markdown: kramdown
future: true
include:
  - _headers
exclude:
  - old-site
  - .bitballoon
  - old_site_concerts_export.xlsx
